### ISSUE TITLE
PHP @ Minestat erroe on socket_recv() line 293

### ISSUE THREAD

**Issue by Deadlineem** [FragLand/minestat#192]
### Expected Behavior
Results from the query to display the server information

### Actual Behavior/Symptoms
After installing the minestat php into my web server, checking php.ini to make sure sockets were allowed and testing the page, it errors out on line 129 and line 293

### How to Reproduce Behavior/Symptoms
Copy the PHP version to a webserver and run it.

### MineStat Version
Latest

### Programming Language and Compiler/Interpreter Version
PHP

### Operating System
Windows 11

### Output/Screenshot(s)

Warning: socket_recv(): Unable to read from socket [10040]: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself in D:\web\server\minestat.php on line 293

Fatal error: Uncaught Error: socket_read(): Argument #1 ($socket) has already been closed in D:\web\server\minestat.php:129 Stack trace: #0 D:\web\server\minestat.php(129): socket_read(Object(Socket), 1) #1 [internal function]: MineStat->__destruct() #2 {main} thrown in D:\web\server\minestat.php on line 129

**Comment by ldilley** [comment]
Does the server you were querying have a public address that you are willing to share, @Deadlineem? This information would be helpful so that I can attempt to query the same address for comparison purposes.

**Comment by Deadlineem** [comment]
@ldilley play.kaosincorporated.com:19132 is the bedrock server, I run that almost 24/7 the Java server is port 25565.  If you visit that url as a web page, there is a status script to show online/offline ad well as at this address (this one uses minestat and takes a little longer to load) http://play.kaosincorporated.com/server-list/

**Comment by ldilley** [comment]
Thank you for the additional information. Are you using PHP 8.x by chance? I do not recall this behavior in 7.x. The root cause: within the destructor, there is an attempt to read 1 byte using the socket to see if it is still open. The socket is already closed at this point due to this line:
https://github.com/FragLand/minestat/blob/1e7b1a6940fe66d4bbaa3519788c6a9c1b29f735/PHP/minestat.php#L306

The error can be ignored since the pertinent data is already obtained prior to the destructor being called. If you want to silence the error, comment or remove these lines:
https://github.com/FragLand/minestat/blob/1e7b1a6940fe66d4bbaa3519788c6a9c1b29f735/PHP/minestat.php#L127-L135

The destructor is unnecessary and was originally written to guarantee that the socket was gracefully shut down and subsequently closed. I'll submit a PR to remove `__destruct()`. Thank you for bringing this to our attention.

**Comment by ldilley** [comment]
Fixed in PR #195. v2.4.1 has also been published to Packagist.

**Comment by Deadlineem** [comment]
@ldilley Minestat rocks, fast fix <3

**Comment by Deadlineem** [comment]
> Thank you for the additional information. Are you using PHP 8.x by chance? I do not recall this behavior in 7.x. The root cause: within the destructor, there is an attempt to read 1 byte using the socket to see if it is still open. The socket is already closed at this point due to this line:
> 
> https://github.com/FragLand/minestat/blob/1e7b1a6940fe66d4bbaa3519788c6a9c1b29f735/PHP/minestat.php#L306
> 
> The error can be ignored since the pertinent data is already obtained prior to the destructor being called. If you want to silence the error, comment or remove these lines:
> 
> https://github.com/FragLand/minestat/blob/1e7b1a6940fe66d4bbaa3519788c6a9c1b29f735/PHP/minestat.php#L127-L135
> 
> The destructor is unnecessary and was originally written to guarantee that the socket was gracefully shut down and subsequently closed. I'll submit a PR to remove `__destruct()`. Thank you for bringing this to our attention.


PHP version 8.0.28

After the update, still getting the 10040 error
http://play.kaosincorporated.com/minestat/example.php

**Comment by ldilley** [comment]
I am unable to reproduce your symptom using MineStat for PHP v2.4.1. I am also no longer able to resolve `play.kaosincorporated.com`. Resolution is spotty depending on DNS server used. Furthermore, your Bedrock server seems to be down currently when I try via IP address or by using `kaosmc.zapto.org`. Below are the results of using another public Bedrock server. There is no more `socket_read()` error. The `socket_recv()` warning might be due to the server sending less data than expected (35 bytes are expected). But, I am still not seeing this warning when I try to query the same 2 Bedrock servers that you shared. I additionally set `error_reporting(E_ALL);` and `error_reporting(E_WARNING);` to explicitly enable warnings to no avail. See below for output.

```
Minecraft server status of 51.81.166.111 on port 25731:<br>Server is online running version 1.20.10 New 1.18 Map! (MCPE) with 3 out of 80 players.<br>Game mode: Survival<br>Message of the day: Menacecraft Survival<br>Message of the day without formatting: Menacecraft Survival<br>Latency: 0ms<br>Connected using protocol: Bedrock/Pocket Edition<br>
```

```
Minecraft server status of bedrock.bosscraft.net on port 19132:<br>Server is online running version 1.20.10 §r§a§lOG PRISON Releasing on The 7th at 3PM CT (MCPE) with 121 out of 2000 players.<br>Game mode: Survival<br>Message of the day: §r§f               §r§b§lʙᴏꜱꜱ§r§4§lᴄʀᴀꜰᴛ§r§e ☺ §r§c1.7-1.20<br>Message of the day without formatting:                ʙᴏꜱꜱᴄʀᴀꜰᴛ ☺ 1.7-1.20<br>Latency: 146ms<br>Connected using protocol: Bedrock/Pocket Edition<br>
```

```
Minecraft server status of play.vulengate.com on port 19132:<br>Server is online running version 1.20.10 §l                §r§9Q§r§9u§r§9e§r§9s§r§bt §r§b+ §r§bJ§r§bo§r§bb§r§bs §r§b+ §r§b1§r§b.§r§b2§r§b0§r§b.§r§b1 (MCPE) with 0 out of 250 players.<br>Game mode: Survival<br>Message of the day: §r§3§lK§r§3§lr§r§3§lu§r§3§lz §r§3§lS§r§3§lu§r§3§lr§r§b§lv§r§b§li§r§b§lv§r§b§la§r§b§ll §r§8§l| §r§bCome Chill!§r<br>Message of the day without formatting: Kruz Survival | Come Chill!<br>Latency: 0ms<br>Connected using protocol: Bedrock/Pocket Edition<br>
```

**Comment by ldilley** [comment]
Nice work on the status page. The 500 error pertains to a misconfiguration on the web server side. If you lack the necessary access to troubleshoot, you can likely submit a ticket with your hosting provider so that they can review the logs. You could also request additional details regarding the `socket_recv()` `10040` error.

**Comment by ldilley** [comment]
Closing due to lack of response.
